[package]
name = "maze_game"
version = "1.0.0"
authors = ["Maze Game Team"]
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[addresses]
maze_game = "0x610b5f5dd4e53876a000fc05432f119bd7763abdb62efc034393ee63055de1f9" 